### ISSUE TITLE
some index out of range...

### ISSUE THREAD

**Issue by breign** [erikbozic/mlm#10]
using mesos master: http://10.0.0.XXX:5050
discovery...
? Selected tasks which you wish to monitor py-drm-dash
panic: runtime error: index out of range

goroutine 10 [running]:
mlm/pkg/monitor.(*Listener).Listen(0xc00006c600, 0xc00016e180, 0xc000076180, 0xc00016e1e0)
	/home/ebozic/src/mesos-monitor/pkg/monitor/listener.go:97 +0x9f6
created by mlm/pkg/monitor.(*Monitor).Start
	/home/ebozic/src/mesos-monitor/pkg/monitor/monitor.go:63 +0x3be

**Comment by breign** [comment]
haha works in 0.0.4
